# Generated by Django 3.1.2 on 2020-10-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('SOLD', 'Item is Sold'), ('OUT OF STOCK', 'Item is out of stock'), ('AVAILABLE', 'Item is ready to be purchased')], default='SOLD', max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('SOLD', 'Item is Sold'), ('OUT OF STOCK', 'Item is out of stock'), ('AVAILABLE', 'Item is ready to be purchased')], default='SOLD', max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
